appName: shippingservice
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/productcatalogservice/shippingservice
appVersion: v0.10.3
appReplicas: 2
containerPort: 50051
containerEnvVars: 
- name: PORT
  value: "50051"

servicePort: 50051
