appName: servicename
appImage: us-central1-docker.pkg.dev/google-samples/microservices-demo/servicename
appVersion: v0.10.3
appReplicas: 1
containerPort: 8080
containerEnvVars: 
- name: ENV_VAR_ONE
  value: "valueone"
- name: ENV_VAR_TWO
  value: "valuetwo"

servicePort: 8080
serviceType: ClusterIP
